name: Deploy to AWS EC2 with Docker

on:
  push:
    branches:
      - main  # main 브랜치에 push 시 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: EC2에 SSH 접속 및 배포 실행
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/pages/manezy_web_page  # 프로젝트 폴더 이동
            git pull origin main  # 최신 코드 가져오기
            docker-compose down  # 기존 컨테이너 중지
            docker-compose up --build -d  # 새 컨테이너 빌드 및 실행
            docker system prune -f  # 불필요한 Docker 파일 정리